name: Sanity Check
run-name: ${{ github.actor }} is running a 'build' workflow

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "üêß This job is running on a ${{ runner.os }} server hosted by GitHub!"
    - uses: actions/checkout@v3
    - run: echo "üí° The ${{ github.repository }} repository has been cloned."
    - run: echo "Setting up JDK" 
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - run: echo "üñ•Ô∏è The workflow is now ready to test your code."
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - run: echo "üêõ Building Debug APK."  
    - name: Build with Gradle
      run: ./gradlew
        -PSIGNING_KEYSTORE_PASSWORD=${{ secrets.SIGNING_KEYSTORE_PASSWORD }}
        -PSIGNING_ALIAS=${{ secrets.SIGNING_ALIAS }}
        -PSIGNING_ALIAS_PASSWORD=${{ secrets.SIGNING_ALIAS_PASSWORD }}
        build
    - run: echo "Build status report=${{ job.status }}."
